### ISSUE TITLE
¿Qué licencia tiene?

### ISSUE THREAD

**Issue by cnngimenez** [qriollo/qriollo#2]
El código no aporta ninguna licencia (normalmente se agrega un archivo COPYING.txt o LICENSE.txt con el texto completo de la licencia). 

Sin licencia no se puede saber de antemano qué está permitido hacer con el código. Ejemplos de licencia podés encontrar en la página de la Free Software Foundation (GNU.org) : http://www.gnu.org/licenses/

**Comment by gciruelos** [comment]
Del manual de Qriollo:

>Licencia Qriolla - 1810-2016, Hermandá Qriolla
>Términos y condiciones:
>Este programa es una MIERDA y se distribuye con la esperanza de que lo uses para LO QUE SE TE CANTE EL ORTO siempre que NO ROMPAS LAS PELOTAS.

**Comment by qriollo** [comment]
Ya agregamos los archivos para distribuir Qriollo bajo la licencia GPLv3.
